apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: anariktestcron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: 10
          containers:
          - name: test
            image: busybox
            args:
            - /bin/bash
            - -c
            - uname  
          restartPolicy: OnFailure  
