apiVersion: v1
kind: Pod
metadata:
  name: nonamepod
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "1Gi"
        cpu: "200m" 
      requests:
        memory: "1Gi"
        cpu: "200m"
